[project]
name = "puffin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate==1.6.0",
    "click==8.1.8",
    "decorator==5.2.1",
    "deepspeed==0.16.7",
    "diffusers==0.34.0",
    "einops==0.8.1",
    "feedparser==6.0.11",
    # "flash-attn==2.3.4",
    "flash-attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.8.3/flash_attn-2.8.3+cu12torch2.7cxx11abiTRUE-cp310-cp310-linux_x86_64.whl",
    "huggingface-hub==0.31.1",
    "hyperframe==6.1.0",
    "idna==3.10",
    "imageio==2.37.0",
    "importlib-metadata==8.7.0",
    "json5==0.12.0",
    "lazy-loader==0.4",
    "lightning-utilities==0.14.3",
    "matplotlib==3.10.1",
    "matplotlib-inline==0.1.7",
    "mmengine==0.10.7",
    "networkx==3.4.2",
    "ninja==1.11.1.4",
    "numpy==2.2.5",
    "opencv-python==4.11.0.86",
    "opencv-python-headless==4.12.0.88",
    "openpyxl==3.1.5",
    "pandas==2.2.3",
    "peft==0.15.2",
    "pillow==11.2.1",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "safetensors==0.5.3",
    "scikit-image==0.25.2",
    "scipy==1.15.2",
    "six==1.17.0",
    "timm==0.9.12",
    "tokenizers==0.21.2",
    "torch==2.7.0",
    "torch-fidelity==0.3.0",
    "torchmetrics==1.7.2",
    "torchvision==0.22.0",
    "tornado==6.4.2",
    "tqdm==4.67.1",
    "transformers==4.49.0",
    "transformers-stream-generator==0.0.5",
    "triton==3.3.0",
    "xtuner==0.1.23",
    "yarl==1.20.0",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126" 
explicit = true 

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }
torchaudio = { index = "pytorch-cu126" }

[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]
